/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.immnl.shn.app.tresor;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void test() {
        new App();
    }
}
