/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.immnl.shn.app.tresor;

import de.immnl.shn.app.tresor.core.Ui.Gui;

public class App {
    public static void main(String[] args) {
        new Gui();
    }
}
